### ISSUE TITLE
bioproject importer doesn't always import

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/tripal_eutils#129]
When I try the example BioProject IDs, I am able to preview the imported metadata - but the preview fails with this ID: 167477

![eutils_error](https://user-images.githubusercontent.com/5487172/52359420-1a838a80-29f7-11e9-98e4-3a02fc6eab6f.png)

**Comment by bradfordcondon** [comment]
weird.  its getting an array when expecting a string.   the array is two keys: attribute (empty array) and value (a 152 empty character string).

I'll download the XML and see what it looks like...

**Comment by bradfordcondon** [comment]
thanks for pointing this out.  Basically we expect LocusTagPrefix to be a single item (which DOES make sense.  generally tags that can be an array of identical tags are inside a "holder" tag.  for example, <Attributes> holds many <Attribute>s).

Anyway.  We now allow for and parse multiple tags, like so: 

![screen shot 2019-02-06 at 2 04 54 pm](https://user-images.githubusercontent.com/7063154/52366640-3b100c80-2a18-11e9-8bf1-375bece8949b.png)

**Comment by bradfordcondon** [comment]
resolved, however, project in general is waiting on some things.  particularly #117
