### ISSUE TITLE
confusion about linked organism values in preview

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/tripal_eutils#134]
This might be a non-issue, just trying to confirm. When creating a linked record from assembly (ID 557018) to the organism table, here's the key/value list:

![linked-records](https://user-images.githubusercontent.com/5487172/52369988-12374980-2a0f-11e9-82b2-83c513860827.png)

THe documentation states that the value of each field should take me to the corresponding record at NCBI. When I click on the organism value, it leads me here, which doesn't seem to contain any information about the organism: http://ontologies.berkeleybop.org/#NCBITaxon:57918

**Comment by bradfordcondon** [comment]
i actually resolved this issue in core.  here's the update:

```php
/**
 * Update the NCBITaxon DB entry.
 */
function tripal_chado_update_7337(){

  chado_insert_db(array(
    'name' => 'NCBITaxon',
    'description' => 'NCBI organismal classification.',
    'url' => 'http://www.berkeleybop.org/ontologies/ncbitaxon/',
    'urlprefix' => 'https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id={accession}',
  ));
}
```

so assuming we use urlprefix instead of url (we do) this should work.  The fact taht the url is wrong for you just means tripal core should be updated on the droplet.  I'll do that now.
