### ISSUE TITLE
discrep between formatter and inserted records

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_eutils#192]
> imported GCA_000188095.3. Said it would import 4 assemblies, 1 organism, 2 bioprojects, 1 biosample. Tripal published 3 bioprojects (1 may have been a leftover project form before?), 0 biosamples, 2 analyses

this is an assembly

**Comment by bradfordcondon** [comment]
| ACCESSION TYPE | VALUE           | CREATED |
|----------------|-----------------| ----------|
| Assembly       | 6127518         |  - [ ]  |
| Assembly       | 6049248         | - [ ]  |
| Assembly       | GCF_000188095.2 | - [ ]  |
| Assembly       | AEQM02          | - [ ]  |
| Organism       | 132113          | - [ ]  |
| Bioprojects    | 61101           | - [ ]  |
| Bioprojects    | 70395           | - [ ]  |
| Biosamples     | 2953787         | - [ ]  |

**Comment by bradfordcondon** [comment]
4 assemblies vs 2 assemblies: GCF_000188095.2 IS 6049248.  AEQM02 IS 6127518. Therefore, *this is a formatter fix*.

**Comment by bradfordcondon** [comment]
i'm going to make a child issue of this for assembly.  Basically its misleading that these are listed as  additional linked records.  one is a WGS xref which goes to nucleotide- i think we want that to go in analysis_dbref.  One is the input accession.  The remaining keys are refseqUID, genbankUID, and refseq accession.  These are kind of all the same analysis... so should be figured out in a separate issue since its quite complciated and i want to restructure the assembly xml parser to be easier to work with for this.

**Comment by bradfordcondon** [comment]
thanks for testing @mpoelchau .  you should find the problem with teh biomaterial not being created resolved.  The issue with the analyses records is a confusing bag of stuff so i made #194 to figure it out

**Comment by mpoelchau** [comment]
Confused because your log message above states that publication records are being imported, but they're not in the ncbi xml afaik and the preview display doesn't list them... That said PMID 25908251 is a bumblebee paper. those pubs don't show up in the tripal content on the droplet if I publish publications.

**Comment by mpoelchau** [comment]
or wait is that because we decided not to import pubs? sorry, need to look back at our comment history.

**Comment by bradfordcondon** [comment]
We did decide to import pubs.
https://github.com/NAL-i5K/tripal_eutils/issues/141

You are right that they arent in the XML for the assembly.  They get imported and linked in the Project.

**Comment by mpoelchau** [comment]
I think it's fine to import them, but the admin user needs to know that they're being imported. You can't tell from the preview. Not sure if it's sufficient to just display it in the log message - even if it's documented that to get the full picture, you need to be viewing the drush log, an admin user could still be unwittingly importing pubs without realizing it if they choose not to read the documentation (guilty as charged).
