### ISSUE TITLE
Assembly xrefs vs primary accessions vs linked records

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_eutils#194]
child of #192 

Assembly parser currently has the following in `$info['accessions']['assembly']`:

* GbUid: as genbank assembly
* RsUid: as Refseq assembly
* WGS: as WGS
* AssemblyAccession as NCBI Assembly

in #192  we had a case where importing GCA_000188095.3 resulted in all 4 of these being imported with different values... but all of them point back to the same UID!

Which are accessions?  which are linked records and therefore separate analsyes that need to be created?  WGS- i dont think thats an asembly at all as its in nucleotide.  we dont have a "dbxref" section of the assembly parser.  we should, and thats where it should go.

so for GCA_000188095.3

| ACCESSION TYPE | VALUE           | CREATED |
|----------------|-----------------| ----------|
| Assembly       | 6127518         |  YES .  this is the refseq UID |
| Assembly       | 6049248         |  YES .  this is the genbank UID |
| Assembly       | GCF_000188095.2 | YES this is the refseq accession  |
| Assembly       | AEQM02          | this is the wGS accession.  I think maybe it should be in its own section (ie just a dbxref, not a linked record)  |

**Comment by mpoelchau** [comment]
As far as I can tell, the GenBank assembly is the same data as the WGS accession, just with different accession numbers. I am not sure why they are separate entities. I suspect that WGS is older, and assembly was added on with some new functionality, based on skimming this article: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4702866/

So - I agree with you that WGS should be a Dbxref of the GenBank assembly (if possible). 

I don't think we can assume that GenBank and RefSeq are identical, so these probably aren't dbxrefs.

**Comment by bradfordcondon** [comment]
>I don't think we can assume that GenBank and RefSeq are identical, so these probably aren't dbxrefs.

ok i agree and that makes sense.  But that also means I dont know what to do with them, because I dont think I can tell which is referring to the accession being imported and which is a link to another accession.

**Comment by bradfordcondon** [comment]
these are all now xrefs.

![screen shot 2019-02-26 at 5 57 11 pm](https://user-images.githubusercontent.com/7063154/53452679-ff9da800-39ef-11e9-85d6-e1b1baf58048.png)


we MIGHT shoot ourselves in the foot if the assembly references a different, distinct, assembly.  but i havent seen a case where thats actually what is going on.
