### ISSUE TITLE
EUtilsBioProjectFormatter->formatLinkedRecords($accessions) prints types

### ISSUE THREAD

**Issue by par12005** [NAL-i5K/tripal_eutils#213]
[Line 116 of `includes/formatters/EUtilsBioProjectFormatter.inc`](https://github.com/NAL-i5K/tripal_eutils/blob/master/includes/formatters/EUtilsBioProjectFormatter.inc#L116) `dpm()`'s the type of each item in `$accessions`. This makes it impossible to Preview Records without messages without making changes to the `$_SESSION['messages']` variable.

The other formatters do not seem to have this issue. I think removing the line referenced above should fix the problem.

**Comment by Ferrisx4** [comment]
Line removed via #215. Closing

**Comment by par12005** [comment]
Thanks @Ferrisx4!
