### ISSUE TITLE
NCBI Data loader warning

### ISSUE THREAD

**Issue by Tenncp** [NAL-i5K/tripal_eutils#214]
Using the NCBI  data loader  with "aassembly" selected and accession number 91111 produces the following warning:

Warning: count(): Parameter must be an array or an object that implements Countable in EUtilsAssemblyParser->getFTPData() (line 206 of /home/cphill/drupal7/sites/all/modules/tripal_eutils/includes/xml_parsers/EUtilsAssemblyParser.inc).

**Comment by Ferrisx4** [comment]
@Tenncp Was this using the "Preview Record" or "Import NCBI Record" button, and other than the Warning that you mentioned, was the loader able to pull anything from NCBI at all?

**Comment by Tenncp** [comment]
It was using the "Import NCBI Record" button.  The loader appeared to load the data from NCBI just fine.

________________________________

**Comment by Tenncp** [comment]
The error is due to a misplaced parenthesis. The warning is eliminated by changing line 206 from
    if (count($values == 0)) {
to
  if (count($values) == 0) {

__

**Comment by Ferrisx4** [comment]
Fixed by #222, closing
