### ISSUE TITLE
Undefined table: arraydesign

### ISSUE THREAD

**Issue by Ferrisx4** [NAL-i5K/tripal_eutils#221]
When executing an import job via Drush, the transaction fails with the following error:

```
WD tripal_chado: PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "arraydesign" does not exist                                                                                                                                             [error]
LINE 1:            SELECT platformtype_id           FROM  arraydesig...
                                                          ^:            SELECT platformtype_id           FROM { arraydesign}           GROUP BY platformtype_id         ; Array
(
)
 in chado_query() (line 1790 of /Library/WebServer/Documents/sites/all/modules/Custom/tripal/tripal_chado/api/tripal_chado.query.api.inc).
```

The `arraydesign` table does exist in the database but the function appears to not be appending the schema to the tablename: 
`SELECT platformtype_id FROM { arraydesign} GROUP BY platformtype_id`

**Comment by almasaeed2010** [comment]
Do you see the space in `{ arraydesign}`? That's the issue.

**Comment by almasaeed2010** [comment]
Wait I think we fixed this issue on the main tripal. Try upgrading tripal to the latest master first.

**Comment by Ferrisx4** [comment]
Ah OK thanks, @almasaeed2010, that seemed to have worked. Apparently I need another pair of eyes.

**Comment by almasaeed2010** [comment]
This issue actually has been bother a lot of people. It might need addressing in Tripal itself since it implements the interpreter. Maybe we could suggest at least documenting that this is a common issue.
