### ISSUE TITLE
FTP Timeouts

### ISSUE THREAD

**Issue by Ferrisx4** [NAL-i5K/tripal_eutils#232]
Recently, FTP requests to NCBI have been timing out. Looking at official documentation now, but it does not seem to be a change on NCBI's system.
An example error from Tripal Eutils attempt:
```
file_get_contents(ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/516/895/GCA_000516895.1_LocustGenomeV1/GCA_000516895.1_LocustGenomeV1_assembly_stats.txt):[warning]
failed to open stream: Failed to set up data channel: Connection timed out EFTP.inc:35
```
However, running file_get_contents with the same resource outside of Tripal (basic PHP) works without issue.
Currently looking into how Tripal Eutils forms the request.

**Comment by dsenalik** [comment]
Closed with merged pull request #246
