### ISSUE TITLE
Namespace and functionality conflict with Tripal Analysis Expression

### ISSUE THREAD

**Issue by Ferrisx4** [NAL-i5K/tripal_eutils#233]
The module uses a generic namespace when loading the NCBI Sample Terms and this conflicts with the same functionality provided by the Tripal Expression Analysis module.
In this module, both the namespace and idspace are `ncbi_properties` whereas in Tripal Analysis Expression module, these are `NCBI Sample Attributes` and `NCBI_Sample_Terms`, respectively.

See the initial discussion here in https://github.com/tripal/tripal_analysis_expression/pull/392#issuecomment-1073030325

The suggested solution by @spficklin and @dsenalik  this:
 - [x] Change this module to use the following format:
namespace: `NCBI BioSample Attributes` (instead of ncbi_properties)
idspace: `NCBI_BioSample_Attritubes` (instead of ncbi_properties)
 - [x] apply an update to convert old data
 - [x] Change how data is loaded from NCBI to be more similar to how it is done in the Tripal Expression Analysis module. It is done on-the-fly in that module instead of loading a hard copy of the XML.

<hr>

Discussion also mentioned the possibility of having this module take on this functionality alone and for the Tripal Expression Analysis module to depend on this module being installed instead, but the above alternative was favored.

**Comment by dsenalik** [comment]
Third item resolved with merged pull request #247

**Comment by dsenalik** [comment]
Testing on an empty tripal 3 site revealed a few install | uninstall issues. Submitting a pull request to fix these.
