### ISSUE TITLE
tagmapper - cache cvterm lookups

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_eutils#29]
https://github.com/NAL-i5K/tripal_eutils/pull/27#pullrequestreview-179830283

@almasaeed2010 noted that we lookup the terms for each and proposed cacheing the lookups which sounds like a great idea to me.

As an alternative, the mapper could instead just send the accession (`local:sex` for example) so the lookup doesnt happen unless we encounter that term... but if we encounter most terms in most lookup (which we do) it would be smarter to pre-cache like you suggest.

**Comment by almasaeed2010** [comment]
see #45
