### ISSUE TITLE
creating linked records

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_eutils#34]
![screen shot 2018-11-29 at 3 07 28 pm](https://user-images.githubusercontent.com/7063154/49248807-94403c00-f3e8-11e8-8dae-968b32ec658f.png)

If a biosample is crosslinked in an assembly, we really want to create teh biosample.

@mestato thinks this pretty definite.  And then the biomaterial module provides the biomaterial value we attached to the analysis....

**Comment by bradfordcondon** [comment]
We want to do this open-ended so that down the road we support creating other types of cross-ref'd records...

**Comment by bradfordcondon** [comment]
Lets say we need to be careful about adding linked records and only want to add thinks DIRECTLY LINKED to the first record.  we could add this constructor to EUTILS:

```
  public function __construct($add_linked) {
  }
```
And then, the EUtils passes this into the Repository when it's called.

Finally, the repository ignores linked records if add_linked is false.

To be clear, $add_linked is pretty much always false, except when the submitted form invokes a Eutils, then it may be true.


However im not sure which behavior is desirable.  For now, lets add ALL linked records.

**Comment by almasaeed2010** [comment]
The idea: if the insert linked records is checked, submit a job to retrieve all the records and insert them

Reasoning: if we have multiple linked records it might take a while + lots of memory to get through them and insert them

**Comment by bradfordcondon** [comment]
is that easier than running everything through a job instead?

**Comment by almasaeed2010** [comment]
that sounds good to me

**Comment by almasaeed2010** [comment]
PR Submitted #105 

missing assembly so I'll leave this open for now

**Comment by bradfordcondon** [comment]
#105 merged so closing issue.
