### ISSUE TITLE
move generic methods to eutilisrepositoryinterface?

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_eutils#39]
biosample repository has a lot of methods that i want ot copy wholesale for bioproject:  `getAccessionByName`, `getDB` for example.  Let's move them into the parent class.  Good indicator is if it doesnt explicitly touch the base table ie biomaterial table, we can move it.

**Comment by almasaeed2010** [comment]
Let's do a base class 😃

**Comment by bradfordcondon** [comment]
clarification: the base class already exists. ill move it in my pR and you can approve or not.

**Comment by bradfordcondon** [comment]
its a base class now, closing.
