### ISSUE TITLE
documentation time

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_eutils#83]
for dev...
write a parser that extends X.  write a formatter that extends Y.  we hardcode the selectbox in the admin form, addi t there.  the db name MUST MATCH the ncbi name.... you need to install a new db into chado.db....

for user...
not much for now.  when we add fields, we'll need docs for that.

**Comment by almasaeed2010** [comment]
RTD or simple README?

**Comment by bradfordcondon** [comment]
I went with RTD.  theres too much to do and its too complicated.  Plus if we can get Breathe integrated we'll be able to use the in-code documentation for classes etc and crossreference it hwich could be super helpful.
