### ISSUE TITLE
get analysis source URI for creating assembly -> analysis

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_eutils#86]
we have source URI via the FTP field for the assembly

**Comment by bradfordcondon** [comment]
well.... the FTP URL is the assembly output and/or the report, which isnt the same as the source URI.  We really run into the same problem we always do with this: if the assembly is 1 analysis and not multiple, what is the input?  The raw reads?  The biosample?  

Really its a problem with the analysis table and the unique field constraints being obnoxious. We need to add a sourcename that will help make this unique or we'll run into trouble as the unique key is sourcename, program, programversion.

Therefore sourcename should either by the biosample accession or the FTP URL, but i dont know we'll always have the biosample.

**Comment by mpoelchau** [comment]
I've been using the Biosample for the assembly analysis source. So, agreed.

**Comment by bradfordcondon** [comment]
thats a relief, great thanks @mpoelchau .  I'm working on documenting my mapping in the docs, we'll have to go over it together and make sure its in line with what you've been doing previously.

https://tripal-eutils.readthedocs.io/en/latest/ncbi_mapping.html#database-specific-mappings
